### ISSUE TITLE
load method missing for class Bvh

### ISSUE THREAD

**Issue by DavidLSmyth** [dabeschte/npybvh#2]
I think you may have forgotten to actually commit and push this

**Comment by FNRocha** [comment]
Having the same problem, not being able to run the code.

**Comment by funnyQZQ** [comment]
Invoke the anim.parse_file function.

**Comment by dabeschte** [comment]
Sorry, notifications for this repository were disabled and I never saw the issues. Yes, seems like the example in the readme was not matching actual function name.
I am sure it is too late for you now, but it is finally corrected. 

Thanks for reporting!
